#! /bin/bash

# run this if you're in a state where you can deal with an update / upgrade.
# you should reboot afterwards

echo "syncing package repo metadata - this may take some time"
sudo apt-get update

echo "upgrading any packages that need it - this may take some time"
sudo apt-get dist-upgrade -y

echo "reboot now!"
