#! /bin/bash

# what machine have we got?
if [ `arch` == "x86_64" ]
then
  export ARCH=64
  export TAG=x86_64
else
  export ARCH=32
  export TAG=x86
fi

echo "Your machine is ${ARCH} bits."
echo ""

# http://conda.pydata.org/miniconda.html
echo "Making sure $HOME/Downloads exists."
mkdir -p $HOME/Downloads
pushd $HOME/Downloads
echo "Removing any old Miniconda3 installers."
rm -f Miniconda3*
echo "Downloading the latest Miniconda3 installer."
wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-$TAG.sh
echo "Download is finished."
popd

echo "Ready to install Miniconda3. Notes:"
echo ""
echo "1. This is a batch install using all the defaults. License approval on"
echo "   your part is assumed."
echo "2. The installer will not overwrite an existing Miniconda3 installation."
echo "   You can ignore the error it throws when it tries."
echo ""

# go for it!
bash $HOME/Downloads/Miniconda3-latest-Linux-$TAG.sh -b

# make sure everything's there for the data science students
echo "Updating the Miniconda distribution."
~/miniconda3/bin/conda update --yes --all

echo ""
echo ""
echo "Creating a Conda environment named 'data-science' with 'django', 'jupyter',"
echo "'seaborn', 'statsmodels' and 'scikit-learn'. This will not overwrite an"
echo "existing 'data-science'. You can ignore the error it throws when it tries."
~/miniconda3/bin/conda create --yes --name data-science \
  django jupyter seaborn statsmodels scikit-learn

echo ""
echo "Installing 'djangorestframework' in 'data-science' with pip."
source $HOME/miniconda3/bin/activate data-science
pip install djangorestframework
source $HOME/miniconda3/bin/deactivate data-science
echo ""
echo "Adding the 'conda', data science activate and deactivate aliases to your"
echo "'.bashrc' file."
cat data-science-aliases >> $HOME/.bashrc
echo "Log out and back in again to define the aliases."
echo ""
echo "To use the data science services, open a terminal and type"
echo ""
echo "    activate-data-science"
echo "    jupyter notebook"
echo ""
echo "A browser will open to your Jupyter notebook server. Type"
echo ""
echo "    deactivate-data-science"
echo ""
echo "after shutting down the notebook server."
echo ""
echo "To start a notebook server on the local area network, type"
echo ""
echo "    activate-data-science"
echo "    jupyter notebook --ip 0.0.0.0 --no-browser"
