#! /bin/bash

# upstream repository
# https://docs.docker.com/engine/installation/linux/ubuntulinux/
echo "Adding the upstream Docker package repository"
sudo cp docker.list /etc/apt/sources.list.d/
sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 \
  --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
sudo apt-get update > /dev/null && sudo apt-file update > /dev/null 2>&1

echo "Installing Docker packages"
sudo apt-get install -y \
  aufs-tools \
  cgroupfs-mount \
  docker-engine \
  linux-image-extra-$(uname -r)

sudo gpasswd -a ${USER} docker && sudo systemctl restart docker
echo "https://apt.dockerproject.org/repo repository added!"
echo "Log out and back in to join the 'docker' group!"
