---
title: "Release Notes - Linux Laptop Setup and VirtualBox / Vagrant Builds"
author: "M. Edward (Ed) Borasky"
date: "2016-11-13"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Overview
I've uploaded a new OVA and a Vagrant box with the same software to the Google Drive. Look for the folder 'Hack Oregon Base v2'. Aside from the enhancements inside, the main user-visible change is that both the OVA and the Vagrant box use the login 'vagrant', not 'hack' like before. They're both about 2 GB.

Instructions for testing / using the Vagrant box are at <https://github.com/hackoregon/getting-started/blob/master/datascience/linux-laptop-setup/Using_the_Vagrant_Box.md>. Please test this if you can and open issues if anything's messed up!

## Closed Issues
* Make an alias for Jupyter in OVA #3: Done - alias is `jupyternb`. This works in both the OVA and the Vagrant box.
* Add 'gdal' and 'libgdal' to the 'data-science' Conda environment #1: done.
* Add instructions for creating a PostGIS extension in OVA #2: Rather than tell people how to do it, the code just does it. ;-) Specifically, the PostgreSQL install script now
    1. Creates a PostgreSQL superuser ('role' in PostgreSQL terminology) named 'vagrant'.
    2. Creates a personal database with the same name - 'vagrant'. This is the default behavior for a "personal" user of PostgreSQL.
    3. Creates the extensions `postgis`, `postgis_topology`, `pgrouting` and `plpython3u`.
* Add instructions for PostgreSQL access in Jupyter #4: The `data-science` Conda environment now includes the Python library to connect to PostgreSQL, called `psycopg2`.
* Prep for Vagrant #8: a full Vagrant box file is now created from the VirtualBox guest machine.
* shrink the OVA #10: The OVA and Vagrant box are 2 GB; previous OVA is 4 GB.
