---
title: "Using the Hack Oregon Base v2 Vagrant Box"
author: "M. Edward (Ed) Borasky <znmeb@znmeb.net>"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Bugs? Feature requests? Unclear documentation?
File an issue at <https://github.com/hackoregon/getting-started/issues/new>.

## System requirements
1. As always, reliable wall power and internet connectivity!
2. A 64-bit host system, preferably with virtualization hardware. This is unlikely to work on a 32-bit host even though there are claims that it will. It's just not worth the hassle.
3. VirtualBox 5.0 or later.
4. Vagrant 1.8.7 or later.

## Obtaining and configuring the base box
1. Install VirtualBox and Vagrant.
2. Download the file - it's in our Google Drive repository. The name is `hackoregon-base-v2.box`.
3. Open a terminal in the directory where you downloaded the `.box` file. Enter
`vagrant box add --provider virtualbox --name hackoregon-base-v2 ./hackoregon-base-v2.box`

    You'll see something like
    ```
    ==> box: Box file was not detected as metadata. Adding it directly...
    ==> box: Adding box 'hackoregon-base-v2' (v0) for provider: virtualbox
        box: Unpacking necessary files from: file:///home/znmeb/vagrant-test/hackoregon-base-v2.box
    ==> box: Successfully added box 'hackoregon-base-v2' (v0) for 'virtualbox'!
    ```
4. Enter `vagrant init hackoregon-base-v2`. You'll see
    ```
    A `Vagrantfile` has been placed in this directory. You are now
    ready to `vagrant up` your first virtual environment! Please read
    the comments in the Vagrantfile as well as documentation on
    `vagrantup.com` for more information on using Vagrant.
    ```
5. Edit the Vagrantfile to add the Jupyter notebook port forwarding. Find the section that looks like this:

    ```
    # Create a forwarded port mapping which allows access to a specific port
    # within the machine from a port on the host machine. In the example below,
    # accessing "localhost:8080" will access port 80 on the guest machine.
    # config.vm.network "forwarded_port", guest: 80, host: 8080
    ```

    Add the line `config.vm.network "forwarded_port", guest: 8888, host: 7777` after the `# config.vm.network` line. It should look like this when you're done


    ```
    # Create a forwarded port mapping which allows access to a specific port
    # within the machine from a port on the host machine. In the example below,
    # accessing "localhost:8080" will access port 80 on the guest machine.
    # config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.network "forwarded_port", guest: 8888, host: 7777
    ```
    
    Save the edited Vagrantfile.

6. Enter `vagrant up --provision --provider virtualbox`. You'll see
    ```
    Bringing machine 'default' up with 'virtualbox' provider...
    ==> default: Importing base box 'hackoregon-base-v2'...
    ==> default: Matching MAC address for NAT networking...
    ==> default: Setting the name of the VM: vagrant-test_default_1479083697149_52159
    ==> default: Clearing any previously set network interfaces...
    ==> default: Preparing network interfaces based on configuration...
        default: Adapter 1: nat
    ==> default: Forwarding ports...
        default: 8888 (guest) => 7777 (host) (adapter 1)
        default: 22 (guest) => 2222 (host) (adapter 1)
    ==> default: Booting VM...
    ==> default: Waiting for machine to boot. This may take a few minutes...
        default: SSH address: 127.0.0.1:2222
        default: SSH username: vagrant
        default: SSH auth method: private key
        default: 
        default: Vagrant insecure key detected. Vagrant will automatically replace
        default: this with a newly generated keypair for better security.
        default: 
        default: Inserting generated public key within guest...
        default: Removing insecure key from the guest if it's present...
        default: Key inserted! Disconnecting and reconnecting using new SSH key...
    ==> default: Machine booted and ready!
    ==> default: Checking for guest additions in VM...
    ==> default: Mounting shared folders...
        default: /vagrant => /home/znmeb/vagrant-test
    ```
7. Enter `vagrant ssh`. You'll be logged into the box as `vagrant`. The box ships with a publicly-known password, `ORturkeyeggs`, for the `vagrant` account. You will need to change it! Enter `passwd`.
    ```
    $ passwd
    Changing password for vagrant.
    (current) UNIX password: 
    Enter new UNIX password: 
    Retype new UNIX password: 
    passwd: password updated successfully
    ```
7. Enter 
    ```
    cd getting-started/datascience/linux-laptop-setup
    git pull
    ./configure-postgresql
    ```

    `git pull` updates the `getting-started` repository to the latest release and `./configure-postgresql` configures the PostgreSQL database. 
    
    First, you will need to set the *PostgreSQL* password for the PostgreSQL `vagrant` superuser. The script will prompt you. Don't use a colon (':') in the password. The configuration file in the next step uses colon as a separator. If you mis-type one of the password entries, just run the script again.
    
    Second, you will need to edit the file `~/.pgpass`. Replace the string 'password' with the password you set above and save the file. This file allows you to connect to the `vagrant` database as the `vagrant` user in a Jupyter notebook without exposing the database password!
    
## Using the configured box
1. Open a terminal in the directory where the Vagrantfile is stored.
2. Enter `vagrant up` if you previously shut the box down with `vagrant halt`. Then enter `vagrant ssh`.
3. Enter `activate-data-science` and then `jupyternb`. You'll see
    ```
    [I 16:41:20.615 NotebookApp] [nb_conda_kernels] enabled, 2 kernels found
    [I 16:41:20.621 NotebookApp] Writing notebook server cookie secret to /run/user/1000/jupyter/notebook_cookie_secret
    [I 16:41:51.427 NotebookApp] [nb_conda] enabled
    [I 16:41:51.681 NotebookApp] ✓ nbpresent HTML export ENABLED
    [W 16:41:51.682 NotebookApp] ✗ nbpresent PDF export DISABLED: No module named 'nbbrowserpdf'
    [I 16:41:51.843 NotebookApp] [nb_anacondacloud] enabled
    [I 16:41:51.876 NotebookApp] Serving notebooks from local directory: /home/vagrant
    [I 16:41:51.877 NotebookApp] 0 active kernels 
    [I 16:41:51.878 NotebookApp] The Jupyter Notebook is running at: http://0.0.0.0:8888/
    [I 16:41:51.878 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
    ```
4. On the host, browse to <http://localhost:7777/tree>. You'll be in the Hack Oregon Jupyter notebook environment!

## Shutdown sequencing
1. Close all the browser tabs using the server.
1. Stop the Jupyter notebook server by typing `Control-C` twice in the terminal where the server is running.
2. Deactivate the environment by entering `deactivate-data-science`.
3. Enter `exit` to log out of the Vagrant box.
4. Enter `vagrant halt` in the host terminal.

## Bugs? Feature requests? Unclear documentation?
File an issue at <https://github.com/hackoregon/getting-started/issues/new>.
