#! /bin/bash

# https://www.vagrantup.com/docs/boxes/base.html
# 

echo "Installing the SSH key for 'vagrant'"
mkdir -p ~vagrant/.ssh
wget -O ~vagrant/.ssh/authorized_keys https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant.pub
chmod 0700 ~vagrant/.ssh
chmod 0600 ~vagrant/.ssh/authorized_keys

echo "Creating the '/vagrant' mount point"
sudo mkdir -p /vagrant
sudo chown -R vagrant:vagrant /vagrant

echo "Disabling reverse DNS lookup for ssh"
sudo sed -i -e "\$aUseDNS no" /etc/ssh/sshd_config
